#!/bin/env inex

exp_dir: exp/local_v2/train_lstm_like5_3.3_alldata_l1
ckpt_bname: "last.ckpt"

plugins:
  - pl_module
  - _inplace_load
  ## DATA
  - dl_split_by_worker
  - dl_tar_to_samples
  - dl_decode
  - dl_prepare_feats
  - dl_filter
  - dl_select_loc
  - dl_control_maxt
  - dl_unbatch
  ## VAL DATA
  - test_tars_list
  - dl_test_tars
  - dl_test_batching
  - dl_test_dataloader
  - dl_predictor
  - dpl_save_submit
  - dpl_write
  ## DEBUG

############ MODEL ###########################

pl_module:                         
  module:  inex.helpers/_import_        
  exports:
    - inplace_load_from_checkpoint
  options:                              
    plugin: pl_module              
    config: ${exp_dir}/final_config.yaml

_inplace_load:
  module: plugins.pl_module/inplace_load_from_checkpoint
  options:
    ckpt_path: ${exp_dir}/${ckpt_bname}


model_averaging:
  module: maa_yacup.average_models/average_model_with_ckpts
  imports:
    module: plugins.pl_module
  options:
    ckpts:
      - exp/local_v2/train_lstm_like5_3.3_alldata_l1/epoch=1-step=13132.ckpt
      - exp/local_v2/train_lstm_like5_3.3_alldata_l1/epoch=7-step=52528.ckpt
     
dl_split_by_worker:
  module: inex.helpers/attribute
  options:
    modname: webdataset
    attname: split_by_worker

dl_tar_to_samples:
  module: webdataset/tarfile_to_samples

dl_decode:
  module: webdataset/decode

dl_prepare_feats:                                          
  module: maa_yacup.data.wds_filters/prepare_input_feats_v2

dl_filter:
  module: maa_yacup.data.wds_filters/filter_keys
  options:
    keep:
      - 'control_feats.pth'
      - 'loc.pth'
      - 'x.pth'
      - 'y.pth'
      - 'yaw.pth'
      - req_stamps.pth
      - start_ns.id

dl_select_loc:
  module: maa_yacup.data.wds_filters/select_loc_columns
  options:
    columns: [0, 1]

dl_control_maxt:
  module: maa_yacup.data.wds_filters/continue_control_up_to
  options:
    maxT: ${dl_predictor.options.end_frame}
    pad_value: ${dl_test_batching.options.collate_fn_kwargs.pad_value}


################## VAL DATALOADER ############
test_tars_list:
  module: glob/glob
  options: 
    pathname: 'exp_v2/YandexCup2024v2/YaCupTest/dump-*.tar'

dl_test_tars:
  module: webdataset/SimpleShardList
  imports:
    urls: plugins.test_tars_list
# tars (/)
# split by node / worker (/)
# tarfile_to_samples
# decode

dl_test_batching:
  module: maa_yacup.data.wds_batching/batching_constant_batch_size
  options:
    batch_size: 32
    collate_fn_kwargs: 
      pad_value: -1000000
# batching

dl_test_dataloader:
  module: maa_yacup.data.wds_dataloaders/build_dataloder
  imports:
    datapipeline:
      - plugins.dl_test_tars
      - plugins.dl_split_by_worker
      - plugins.dl_tar_to_samples
      - plugins.dl_decode
      - plugins.dl_prepare_feats
      - plugins.dl_filter
      - plugins.dl_select_loc
      - plugins.dl_control_maxt
      - plugins.dl_test_batching
  options:
      num_workers: 8
      pin_memory: True
      batch_size: null
      sampler: null


dl_predictor:
  module: maa_yacup.wds_predict/predict
  imports:
    module: plugins.pl_module
  options:
    device: cuda
    limit: -1
    start_frame: 245
    end_frame: 1020
    aprox_yaw: True

dl_unbatch:
  module: maa_yacup.data.wds_batching/unbatch
  options:
    pad_value: ${dl_test_batching.options.collate_fn_kwargs.pad_value}

dpl_save_submit:
  module: maa_yacup.data.wds_filters/save_submit
  options:
    outd: ${exp_dir}/submits
    loc_key: "predicted.pth"
    frame_step: 20000000

dpl_write:                                                 
  module: maa_yacup.data.wds_filters/write_as_sharded_wds 
  options:                                                
    out_printf_frmt: ${exp_dir}/submits/last-%06d.tar   
    max_elements_per_shard: 1000                          

execute:
  method: maa_yacup.data.wds_pipelines/run
  imports:
    pipeline: 
      - plugins.dl_test_dataloader
      - plugins.dl_predictor
      - plugins.dl_unbatch
      - plugins.dpl_save_submit
      - plugins.dpl_write
