#!/bin/env inex

exp_dir: exp/local_v2/train_lstm_like5_3.2
ckpt_bname: last.ckpt

plugins:
  - pl_module
  - _inplace_load
  ## DATA
  - dl_split_by_worker
  - dl_tar_to_samples
  - dl_decode
  - dl_prepare_feats
  - dl_filter
  - dl_select_loc
  - dl_chunking
  - dl_control_maxt
  - dl_unbatch
  ## VAL DATA
  - val_tars_list
  - dl_val_tars
  - dl_val_batching
  - dl_val_dataloader
  - dl_predictor
  - dl_score
  - dl_save_submit
  - dl_write
  ## DEBUG

############ MODEL ###########################

pl_module:                         
  module:  inex.helpers/_import_        
  exports:
    - inplace_load_from_checkpoint
  options:                              
    plugin: pl_module              
    config: ${exp_dir}/final_config.yaml

_inplace_load:
  module: plugins.pl_module/inplace_load_from_checkpoint
  options:
    ckpt_path: ${exp_dir}/${ckpt_bname}


################## DATALOADERS ###############
#split_by_node:
#  module: inex.helpers/attribute
#  options:
#    modname: webdataset
#    attname: split_by_mode

dl_split_by_worker:
  module: inex.helpers/attribute
  options:
    modname: webdataset
    attname: split_by_worker

dl_tar_to_samples:
  module: webdataset/tarfile_to_samples

dl_decode:
  module: webdataset/decode

dl_prepare_feats:                                          
  module: maa_yacup.data.wds_filters/prepare_input_feats_v2

dl_filter:
  module: maa_yacup.data.wds_filters/filter_keys
  options:
    keep:
      - 'control_feats.pth'
      - 'loc.pth'
      - 'x.pth'
      - 'y.pth'
      - 'yaw.pth'
      - 'start_ns.id'

dl_select_loc:
  module: maa_yacup.data.wds_filters/select_loc_columns
  options:
    columns: [0, 1]

dl_chunking:                                 
  module: maa_yacup.data.wds_filters/chunking
  options:                                   
    chunk_len: 1000
    shift: 250                               

dl_control_maxt:
  module: maa_yacup.data.wds_filters/continue_control_up_to
  options:
    maxT: ${dl_predictor.options.end_frame}
    pad_value: ${dl_val_batching.options.collate_fn_kwargs.pad_value}


################## VAL DATALOADER ############
val_tars_list:
  module: glob/glob
  options: 
  #pathname: 'exp_v2/YandexCup2024v2/YaCupTrain/dump-0001*.tar'
    pathname: 'exp_v2/YandexCup2024v2/val/dump-*.tar'

dl_val_tars:
  module: webdataset/SimpleShardList
  imports:
    urls: plugins.val_tars_list
# tars (/)
# split by node / worker (/)
# tarfile_to_samples
# decode

dl_val_batching:
  module: maa_yacup.data.wds_batching/batching_constant_batch_size
  options:
    batch_size: 1 #10
    collate_fn_kwargs: 
      pad_value: -1000000
# batching

dl_val_dataloader:
  module: maa_yacup.data.wds_dataloaders/build_dataloder
  imports:
    datapipeline:
      - plugins.dl_val_tars
      - plugins.dl_split_by_worker
      - plugins.dl_tar_to_samples
      - plugins.dl_decode
      - plugins.dl_prepare_feats
      - plugins.dl_filter
      - plugins.dl_select_loc
      - plugins.dl_chunking
      - plugins.dl_control_maxt
      - plugins.dl_val_batching
  options:
      num_workers: 6
      pin_memory: True
      batch_size: null
      sampler: null


dl_predictor:
  module: maa_yacup.wds_predict/predict
  imports:
    module: plugins.pl_module
  options:
    device: cpu
    limit: 30
    start_frame: 245
    end_frame: 1020
    aprox_yaw: True

dl_unbatch:
  module: maa_yacup.data.wds_batching/unbatch
  options:
    pad_value: -1000000

dl_score:
  module: maa_yacup.wds_score/measure_score


dl_save_submit:
  module: maa_yacup.data.wds_filters/save_submit
  options:
    outd: ${exp_dir}/val
    loc_key: "predicted.pth"
    frame_step: 20000000


dl_write:
  module: maa_yacup.data.wds_filters/write_as_sharded_wds
  options:
    out_printf_frmt: ${exp_dir}/val/validation-%06d.tar
    max_elements_per_shard: 1000


execute:
  method: maa_yacup.data.wds_pipelines/run
  imports:
    pipeline: 
      - plugins.dl_val_dataloader
      - plugins.dl_predictor
      - plugins.dl_unbatch
      - plugins.dl_score
      - plugins.dl_save_submit
      - plugins.dl_write
